"""add_accepted_terms_version

Revision ID: 035ad540ef66
Revises: f6289ac1e3c9
Create Date: 2026-07-29 11:04:36.079167

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "035ad540ef66"
down_revision: str | Sequence[str] | None = "f6289ac1e3c9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("accepted_terms_version", sa.String(length=50), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "accepted_terms_version")
    # ### end Alembic commands ###
