"""add pagarme metadata to user

Revision ID: 541895e61ee0
Revises: 73192ebfcc58
Create Date: 2026-05-18 17:46:19.316225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '541895e61ee0'
down_revision: Union[str, Sequence[str], None] = '73192ebfcc58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pagarme_customer_id', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('subscription_id', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('subscription_status', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('subscription_period_end', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_users_pagarme_customer_id'), 'users', ['pagarme_customer_id'], unique=False)
    op.create_index(op.f('ix_users_subscription_id'), 'users', ['subscription_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_subscription_id'), table_name='users')
    op.drop_index(op.f('ix_users_pagarme_customer_id'), table_name='users')
    op.drop_column('users', 'subscription_period_end')
    op.drop_column('users', 'subscription_status')
    op.drop_column('users', 'subscription_id')
    op.drop_column('users', 'pagarme_customer_id')
    # ### end Alembic commands ###
