"""add subscription_period_start to user

Revision ID: 5e82f25771bc
Revises: 541895e61ee0
Create Date: 2026-05-19 14:16:10.420572

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e82f25771bc'
down_revision: Union[str, Sequence[str], None] = '541895e61ee0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('subscription_period_start', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'subscription_period_start')
    # ### end Alembic commands ###
