"""model option for chat

Revision ID: 7b677b5054b2
Revises: 86be1f259be8
Create Date: 2026-04-01 17:22:39.835215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b677b5054b2'
down_revision: Union[str, Sequence[str], None] = '86be1f259be8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_password_reset_tokens_token'), 'password_reset_tokens', ['token'], unique=True)
    op.add_column('chats', sa.Column('llm_model', sa.String(length=255), nullable=True))
    op.add_column('chats', sa.Column('llm_provider', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_chats_llm_model'), 'chats', ['llm_model'], unique=False)
    op.create_index(op.f('ix_chats_llm_provider'), 'chats', ['llm_provider'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chats_llm_provider'), table_name='chats')
    op.drop_index(op.f('ix_chats_llm_model'), table_name='chats')
    op.drop_column('chats', 'llm_provider')
    op.drop_column('chats', 'llm_model')
    op.drop_index(op.f('ix_password_reset_tokens_token'), table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    # ### end Alembic commands ###
