"""add tag/slug for chat type

Revision ID: 944912616179
Revises: 2a3c0d4f5709
Create Date: 2026-04-13 09:54:40.041717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '944912616179'
down_revision: Union[str, Sequence[str], None] = '2a3c0d4f5709'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_type_tags',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('chat_type_id', sa.Uuid(), nullable=False),
    sa.Column('tag', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['chat_type_id'], ['chat_types.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_type_tags_chat_type_id'), 'chat_type_tags', ['chat_type_id'], unique=False)
    op.create_index(op.f('ix_chat_type_tags_id'), 'chat_type_tags', ['id'], unique=False)
    op.create_index(op.f('ix_chat_type_tags_tag'), 'chat_type_tags', ['tag'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chat_type_tags_tag'), table_name='chat_type_tags')
    op.drop_index(op.f('ix_chat_type_tags_id'), table_name='chat_type_tags')
    op.drop_index(op.f('ix_chat_type_tags_chat_type_id'), table_name='chat_type_tags')
    op.drop_table('chat_type_tags')
    # ### end Alembic commands ###
