"""make_chat_type_id_nullable

Revision ID: ae45ec828b85
Revises: 035ad540ef66
Create Date: 2026-07-30 10:19:34.823516

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ae45ec828b85"
down_revision: str | Sequence[str] | None = "035ad540ef66"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("chats", "chat_type_id", existing_type=sa.UUID(), nullable=True)
    op.drop_constraint(op.f("chats_chat_type_id_fkey"), "chats", type_="foreignkey")
    op.create_foreign_key(
        None, "chats", "chat_types", ["chat_type_id"], ["id"], ondelete="SET NULL"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "chats", type_="foreignkey")
    op.create_foreign_key(
        op.f("chats_chat_type_id_fkey"),
        "chats",
        "chat_types",
        ["chat_type_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.alter_column("chats", "chat_type_id", existing_type=sa.UUID(), nullable=False)
    # ### end Alembic commands ###
