"""add_accepted_terms_at_to_user

Revision ID: bd5eee6b63cf
Revises: ae45ec828b85
Create Date: 2026-09-23 10:58:18.560328

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bd5eee6b63cf"
down_revision: str | Sequence[str] | None = "ae45ec828b85"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("accepted_terms_at", sa.DateTime(timezone=True), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "accepted_terms_at")
    # ### end Alembic commands ###
