"""add_2fa_columns

Revision ID: f6289ac1e3c9
Revises: 23d3382df502
Create Date: 2026-07-27 09:04:34.772546

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f6289ac1e3c9"
down_revision: str | Sequence[str] | None = "23d3382df502"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("two_factor_secret", sa.String(length=32), nullable=True)
    )
    op.add_column(
        "users", sa.Column("two_factor_enabled", sa.Boolean(), nullable=False)
    )
    op.add_column(
        "users",
        sa.Column("last_2fa_reminder_at", sa.DateTime(timezone=True), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "last_2fa_reminder_at")
    op.drop_column("users", "two_factor_enabled")
    op.drop_column("users", "two_factor_secret")
    # ### end Alembic commands ###
